name: python matrix
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        versions: ["3.10","3.11","3.12"]
    steps:
      - name: clone github
        uses: actions/checkout@v4
      - name: install-python
        uses: actions/setup-python@v7
        with:
          python-versions: ${{ matrix.versions }}
      - name: list files
        run: ls -a > text.pdf
      - name: save files
        run: cat text.pdf

 
